### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by efe373** [inmicro/Face-Mask-Detection-Raspberry-pi-2021#3]
Hi,

I have done everything you mentioned, but I am encountering a problem.

`(test) pi@B4M:~/Face-Mask-Detection-Raspberry-pi-2021 $ python3 detect_mask_video.py
2021-03-07 22:16:22.316468: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
[INFO] loading face detector model...
[INFO] loading face mask detector model...
Traceback (most recent call last):
  File "detect_mask_video.py", line 98, in <module>
    maskNet = load_model(args["model"])
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'`

Thanks

**Comment by efe373** [comment]
When I remove the `.decode(utf-8)`, it resolves but other problems are popping.
`
(test) pi@B4M:~/Face-Mask-Detection-Raspberry-pi-2021 $ python3 detect_mask_video.py
2021-03-07 22:25:38.617691: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
[INFO] loading face detector model...
[INFO] loading face mask detector model...
Traceback (most recent call last):
  File "detect_mask_video.py", line 98, in <module>
    maskNet = load_model(args["model"])
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 263, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 234, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional
`
